### ISSUE TITLE
Add a link to a mod installer.

### ISSUE THREAD

**Issue by megalon** [beat-saber-modding-group/BeatMods-Website#13]
Add a link to either of the Mod Installers in the sidebar, or maybe a more prominent button somewhere else.

Beat Saber Mod Manager
https://github.com/beat-saber-modding-group/BeatSaberModInstaller/releases/latest

Beat Drop
https://github.com/StarGazer1258/BeatDrop/releases/latest

**Comment by raftario** [comment]
I'll do that and the game version support together.
