### ISSUE TITLE
Add a landing page for Beat Mods with basic info.

### ISSUE THREAD

**Issue by megalon** [beat-saber-modding-group/BeatMods-Website#14]
When users visit https://beatmods.com they are immediately forwarded to https://beatmods.com/#/mods and shown the list of mods with no instructions on how to install them.

https://beatmods.com/ should really have a landing page with basic install instructions and useful links.

Really basic example
```
**Beat Mods**

This is a mod repository for Beat Saber!

If you need help installing mods, visit
https://bsmg.wiki/beginners-guide
```

**Comment by raftario** [comment]
I'll do that with the other stuff.
