### ISSUE TITLE
Production website running in development mode

### ISSUE THREAD

**Issue by opl-** [beat-saber-modding-group/BeatMods-Website#5]
It appears the production website is currently running on a development build. This means that its code is not minified and includes everything from whitespace to random bits of code in the react library that are intended to aid in development, but only slow down the website when it's being used by the end users.

Is there any reason for this? I believe that even if the website is in a beta stage of its development, you should be serving the production build for the sake of your users.

**Comment by williums** [comment]
Finally fixed with #18 and #21
