### ISSUE TITLE
List predefined categories instead of letting users enter arbitrary category names.

### ISSUE THREAD

**Issue by megalon** [beat-saber-modding-group/BeatMods-Website#7]
Instead of letting users enter whatever category they want into the categories field, use a list of predefined categories. 
Ideally this list could be modified by Beat Mods admins.

Here is StarGazer's suggested list of categories
```
Core
Cosmetic
Practice / Training
Gameplay
Stream Tools
Libraries
UI Enhancements
Lighting
Tweaks / Tools
Multiplayer
Text Changes
Other
```

**Comment by williums** [comment]
Addressed in the last PR
